"""Update current project handoffs after audited Session A; preserve past reports."""
from pathlib import Path
import json
import hashlib
import datetime
import re
ROOT=Path(__file__).resolve().parents[1]

def insert(name,text):
    p=ROOT/name; old=p.read_text(encoding='utf-8')
    if text in old or (text.startswith('## ') and text.split('\n')[0] in old): return
    first,rest=old.split('\n',1); p.write_text(first+'\n\n'+text+'\n\n'+rest.lstrip('\n'),encoding='utf-8')

def main():
    a=json.loads((ROOT/'results/exp009/analysis.json').read_text()); assert a['all_archives_replayed_exactly']
    p=a['primary']; finding=f"compensation improves correct-valence choice probability by {100*p['mean']:.2f} pp [{100*p['interval'][0]:.2f}, {100*p['interval'][1]:.2f}] (95% paired task-block interval)"
    gate='passed' if a['gate_passed'] else 'not met'
    lead=f"**Session A complete — EXP-009 audited, 15 September 2026.** The bounded author-parameter positive control {gate} its gate: {finding}. This is a fresh-task adaptation conditional on one supplied author model, not exact Figure 4 reproduction. [Final report](experiments/EXP-009-results.md). **Next: Session B's representation-versus-learning diagnostic**, following [the saved handoff](research/SESSION_B_HANDOFF.md). Session B has not started; its gate-dependent sequence supersedes the older immediate-next-action wording below."
    insert('README.md',lead)
    insert('ROADMAP.md',lead)
    insert('EXPERIMENTS.md',f"## EXP-009 / Session A — complete, 2026-09-15\n\n[Protocol](experiments/EXP-009-protocol.md) and [report](experiments/EXP-009-results.md): seven validation tests, author-runtime comparison, four development and 24 confirmation blocks, all archives replayed. {finding.capitalize()}. Gate {gate}; author-parameter adaptation, not exact published reproduction. Next: [Session B](research/SESSION_B_HANDOFF.md).")
    insert('DECISIONS.md',f"## 2026-09-15 — D038: close Session A at its decision gate\n\n{finding.capitalize()}. The bounded positive-control gate is {gate}. Permit B to bridge to this supplied-parameter regime only; the twenty-model figure and homeostatic optimizer remain unreproduced. The supplied projection gain is5x versus4.5x in current author source, so retain the fitted artifact and disclose the mismatch. Prior EXP-007/008 nulls remain unchanged. Stop A without running B. [Report](experiments/EXP-009-results.md).\n\n## 2026-09-15 — D037: execute the complete bounded Session A milestone\n\nUser authorized source audit, prospective protocol, implementation, validation, bounded local/free run and final handoff, ending at A's gate. Select Abdelrahman et al. Figure4B2 threshold-compensated versus random model, c=1. Use one supplied author-fitted instance with fresh held-out tasks, explicitly adapting data generation/scaling and rate selection. Preserve failed access attempts and source mismatches; do not silently substitute an exact-reproduction claim. [Protocol](experiments/EXP-009-protocol.md).")
    insert('REPRODUCTIONS.md',f"## R08 / EXP-009 — bounded author-parameter positive control, 2026-09-15\n\n{finding.capitalize()}; gate {gate}. Supplied-input response/learning/decision arithmetic agrees with GNU Octave within1.17e-15. Seven tests and all152 development/confirmation readout replays pass. **Exact Figure4 ensemble and joint calibration optimizer remain NOT REPRODUCED.** One supplied calibrated model, fresh tasks, declared independent adapters, source/fitted-scale mismatch preserved. [Source audit](research/SESSION_A_SOURCE_AUDIT.md), [report](experiments/EXP-009-results.md). This updates the register without changing older reproduction entries.")
    insert('CLAIMS_LEDGER.md',f"## Session A claim update — 2026-09-15\n\n- **Supported internal result:** {finding}, conditional on one author-fitted model and fresh tasks. [EXP-009](experiments/EXP-009-results.md).\n- **Supported arithmetic validation:** SI Eq.3/20/21 port agrees with supplied-input Octave reference within1.17e-15. The optimizer is not validated.\n- **Unsupported:** exact Figure4 reproduction; threshold-only causal effect; explanation/refutation of published compensation; identification of the cause of EXP-007/008 nulls; inference across networks or biological animals.\n- **Next hypotheses only:** pre-existing input normalization/limited residual compensation, and error-dependent readout interference. [Session B handoff](research/SESSION_B_HANDOFF.md).")
    insert('OPEN_QUESTIONS.md',"## Current questions after Session A — 2026-09-15\n\nQ15: Does baseline per-cell input normalization leave too little useful imbalance for bounded offsets to address? Q16: Can a matched-access offline/supervised readout recover representations whose old pair margins fail under chosen-action delta learning? [Session B handoff](research/SESSION_B_HANDOFF.md) defines the next diagnostic; neither explanation is established. Q17: Why does the supplied author model use5x excitation where the current script uses4.5x, and can the full calibration/figure ensemble be regenerated? This limits exact-reproduction claims, not the completed supplied-parameter positive control. The older immediate-next-action wording below is superseded by the sequential A–D plan.")
    insert('FAILED_PATHS.md',"## Session A observations preserved — 2026-09-15\n\nThe exact-reproduction route was narrowed prospectively to an author-parameter adaptation. The supplied calibrated file has5x excitation versus4.5x in the current source; model seeds, complete calibrated ensemble and exact figure-rate mapping were not identified. The optimizer was not rerun. This is an unresolved provenance limitation, not a refutation. No numerical run or unfavorable confirmation block was discarded.\n\nAccess/runtime failures: restricted public sockets, nonexistent master branch, PMC/PNAS challenges, web PDF screenshot cache miss and absent SciPy; resolved with public download escalation, pinned main, Europe PMC, local rendering and existing Octave. Octave emitted a cleanup warning with exit0; numerical fixtures passed. The old archival hashing job outlived its tool session during the user's continuation but completed its manifest; no experimental blocks were rerun to replace data. Historical snapshot started before validation but completed after confirmation; report this timing deviation rather than claiming a completed pre-run freeze. Final checks compare every historical hash. [Audit](research/SESSION_A_SOURCE_AUDIT.md), [report](experiments/EXP-009-results.md).")
    insert('DATA_PROVENANCE.md',"## Session A source bundle — 2026-09-15\n\n[Source audit](research/SESSION_A_SOURCE_AUDIT.md) pins Abdelrahman et al. repository commit9f3f7e9e85117febef1ad32e3152c830570f74d3, supplied fitted MAT instance, Hallem-Olsen PN table, MATLAB methods/noise/evaluator, published PDF, SI and Dataset S1. [Hash manifest](research/exp009_source_audit.json). GPL license and original bytes retained. One supplied calibrated instance is conditioning information, not a newly sampled animal. Saved labels are not reused for new learning. New prototype/noise/label streams and training-only scaling are declared in EXP-009. Source code says4.5x while saved weights are5x; no silent correction.")
    insert('SOFTWARE_AUDIT.md',"## Session A selected compensation dependency — 2026-09-15\n\nThe previous deferral of Abdelrahman's repository is superseded for EXP-009 only. Pinned commit9f3f7e9e85117febef1ad32e3152c830570f74d3, GPL-3.0 source retained, GNU Octave11.3.0 supplied-input reference executed. NumPy implements SI Eq.3/20/21 and author noise lookup; no execution/validation of the joint calibration optimizer. [Audit](research/SESSION_A_SOURCE_AUDIT.md), [validation](results/exp009/validation.json).")
    insert('research/SEARCH_LOG.md',"## 2026-09-15 — Session A targeted compensation audit\n\nInspected Abdelrahman et al. published Figure4/complete caption, SI input/coding/learning/threshold-fitting methods and Eq.3/20/21/65, Dataset S1 Fig4 I3:I22 and M3:M22, and pinned author source/data. Search: `Abdelrahman Vasilaki Lin 2021 compensation github code`. Retrieved source tree/main commit through GitHub API and raw files; Europe PMC supplement mirror resolved PNAS challenge. No broad literature resurvey or novelty claim. [Source audit](SESSION_A_SOURCE_AUDIT.md) distinguishes extracted published values, supplied model, numerical validation and bounded adaptation. Exact figure ensemble and optimizer remain unvalidated.")
    insert('RESEARCH_LOG.md',f"## 2026-09-15 — Session A completed at decision gate\n\nUser authorized the full milestone and later requested continuation after a token interruption. Read current records and actual code/reports; selected Abdelrahman Figure4B2, c=1, threshold compensation versus random. Pinned source, SI, published numerical data and one supplied fitted model. Preserved a5x saved-weight versus4.5x source discrepancy. Wrote prospective EXP-009 protocol; implemented independent fresh tasks and training-only scaling, with author equations and supplied fitted parameters.\n\nSeven tests passed; max author-runtime error1.17e-15. Four development blocks selected eta.001/.001778; fixed24 confirmation blocks completed. All152 readout evaluations replayed exactly and {a['historical_files_verified']:,} historical files verified. {finding.capitalize()}. Positive-control gate {gate}; **not exact Figure4 reproduction**. No fresh optimizer/ensemble or biological replication.\n\nHistorical hash snapshot began before validation but finished after confirmation; final verification passed and no old scientific files were edited. The token continuation reused saved runs/settings. Literature/source preparation, file-hash I/O and reporting are separate from measured model costs. [Report](experiments/EXP-009-results.md), [run](research/runs/EXP-009-positive-control.json).\n\nStop at A. Next: [Session B diagnostic](research/SESSION_B_HANDOFF.md), prioritizing normalization/limited compensation and representation-versus-readout loss with matched supervision and norm controls. Session B has not launched; earlier immediate task-family expansion recommendations are superseded by the A–D gates.")
    manifest=ROOT/'research/experiment_manifest.json'; m=json.loads(manifest.read_text())
    if not any(e['id']=='EXP-009' for e in m['experiments']):
        m['experiments'].append(dict(id='EXP-009',status='completed_audited',session='A',spec='experiments/EXP-009-protocol.md',results='experiments/EXP-009-results.md',run='research/runs/EXP-009-positive-control.json',source_ids=['S68'],validation_tests=7,development_blocks_completed=4,confirmation_blocks_completed=24,primary=p,gate_passed=a['gate_passed'],reproduction_class='independent bounded author-parameter adaptation; equation-level author-runtime validation',next_action='Session B per research/SESSION_B_HANDOFF.md; do not claim exact Figure 4 reproduction'))
        m['scientific_experiments_completed']+=1
    for entry in m['experiments']:
        if entry['id']=='EXP-009':
            entry['status']='completed'
            entry['runtime_measured']=True
    m['date']='2026-09-15'; manifest.write_text(json.dumps(m,indent=2)+'\n',encoding='utf-8')
    refs=ROOT/'research/references.json'; rr=json.loads(refs.read_text(encoding='utf-8'))
    for ref in rr:
        if ref['id']=='S68':
            ref.update(read_depth='published_Figure4_SI_methods_DatasetS1_author_source_and_fixture',accessed='2026-09-15',internally_reproduced=False,internal_validation='EXP-009: supplied-parameter positive control and Eq3/20/21 validation; not exact figure/optimizer reproduction',source_audit='research/SESSION_A_SOURCE_AUDIT.md')
    refs.write_text(json.dumps(rr,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
    # Tight-number spacing in the new dated sections only; preserve older records.
    names=['README.md','ROADMAP.md','EXPERIMENTS.md','DECISIONS.md','REPRODUCTIONS.md','CLAIMS_LEDGER.md','OPEN_QUESTIONS.md','FAILED_PATHS.md','DATA_PROVENANCE.md','SOFTWARE_AUDIT.md','RESEARCH_LOG.md','research/SEARCH_LOG.md']
    for name in names:
        path=ROOT/name; text=path.read_text(encoding='utf-8')
        # Explicit local substitutions do not touch experiment identifiers or hashes.
        for before,after in [('Figure4','Figure 4'),('within1.17','within 1.17'),('all152','all 152'),('has5x','has 5x'),('use5x','use 5x'),('is5x','is 5x'),('are5x','are 5x'),('versus4.5x','versus 4.5x'),('uses4.5x','uses 4.5x'),('says4.5x','says 4.5x'),('a5x','a 5x'),('exit0','exit 0'),('commit9f3','commit 9f3'),('Octave11.3','Octave 11.3'),('error1.17','error 1.17'),('eta.001','eta .001'),('fixed24','fixed 24'),('All152','All 152')]: text=text.replace(before,after)
        path.write_text(text,encoding='utf-8')
    print(f'Updated records: {finding}; gate {gate}')

if __name__=='__main__': main()
