"""Publish the audited EXP-006 local research handoff; no experiments run here."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import json
import numpy as np
from exp006.campaign import ROOT, read, write, folder, interval
from exp002.data import sha256
from exp006.memory import FAMILIES, METRICS, LOADS, OVERLAPS, REGIMES


def replace(path, old, new):
    p = ROOT/path; text = p.read_text(encoding='utf-8')
    if old not in text:
        assert new in text, f'Missing replacement in {path}'
        return
    p.write_text(text.replace(old, new), encoding='utf-8')


def prepend(path, heading, text):
    p = ROOT/path; old = p.read_text(encoding='utf-8')
    if text not in old: p.write_text(old.replace(heading, heading+'\n\n'+text, 1), encoding='utf-8')


def fmt(x):
    return f"{100*x['mean']:.2f} [{100*x['interval'][0]:.2f}, {100*x['interval'][1]:.2f}]"


def main():
    a = read(folder('confirmation')/'analysis.json')
    g = read(folder('confirmation')/'geometry.json')
    run = read(ROOT/'research/runs/EXP-006-confirmation.json')
    dev = read(ROOT/'research/runs/EXP-006-development.json')
    contract = read(folder('confirmation')/'contract.json')
    scores = []
    for b in contract['blocks']:
        with np.load(folder('confirmation')/f'block_{b}.npz') as raw:
            scores.append(raw['scores'][:, :, 0])
    scores = np.array(scores)
    costs = scores[:, 11, :, 0]-scores[:, 11, :, 4]
    noise_costs = {'scope': 'descriptive post-confirmation diagnostic, load16/overlap6/128 per pair', 'cost_definition': 'retention at sigma .1 minus retention at sigma .3', 'profiles': {f: interval(costs[:, i]) for i, f in enumerate(FAMILIES)}, 'k6_minus_k4_cost': interval(costs[:, 1]-costs[:, 0]), 'source_sha256': sha256(Path(__file__))}
    write(folder('confirmation')/'noise_costs.json', noise_costs)
    run['artifact_hashes']['results/exp006_confirmation/noise_costs.json'] = sha256(folder('confirmation')/'noise_costs.json')
    run['supplementary_reporting_source_sha256'] = sha256(Path(__file__))
    write(ROOT/'research/runs/EXP-006-confirmation.json', run)
    names = {'native4': 'Native K4', 'native6': 'Native K6', 'direct': 'Direct input', 'random4': 'Random K4', 'random6': 'Random K6', 'oracle': 'Identity oracle'}
    lines = ['# EXP-006: persistent-memory load and similarity — audited results', '',
        '2026-09-14. Priority 2 complete: six development and 32 confirmation blocks; nine preflight tests, complete task/metric audits, exact full-block replay in both stages. No weight resets between memories or during reversal. No performance-based exclusions, retuning or sample extension.', '',
        '[Frozen protocol](EXP-006-protocol.md) · [analysis and intervals](../results/exp006_confirmation/analysis.json) · [audited run](../research/runs/EXP-006-confirmation.json) · [all profile values](../results/exp006_confirmation/profiles.csv) · [memory-age table](../results/exp006_confirmation/memory_age.csv)', '',
        '## What the experiment establishes', '',
        'Six winners continue to help under persistent memory, including noisy probes. At 16 similar cue pairs with 128 presentations per pair, K6 retains 78.74% versus K4 71.14%: +7.60 percentage points [4.68,10.43], primary 98.75%. At noise .3, the advantage is +6.06 pp [3.61,8.31]. This preserves the useful K6 direction from EXP-005 under a substantially different memory task.', '',
        'The important limit is cumulative forgetting. K6 immediately learns the similar pairs at 98.65% on average, then retains only 78.74% after all 16 pairs. Its retention falls 18.22 pp [14.05,22.21] from load2 to load16 despite constant exposure per pair. Learning later pairs therefore damages earlier associations; the load cost cannot be attributed simply to fewer presentations per memory.', '',
        'Direct input reaches 85.88% retention in that condition with 80 learned weights versus 146 for sparse circuits. Its descriptive paired advantage over native K6 is +7.15 pp [4.83,9.36], 95%. Direct input also has better noisy retention and reversal profiles. The input contains usable information that the tested sparse encoding plus readout-learning setup does not retain as effectively. This does not identify whether representation collisions, shared-feature updates, or bounded optimization is the unique cause.', '',
        'The additional similarity penalty predicted for K6 was not established: at load16, overlap6 minus overlap2 retention is -0.02 pp [-5.21,5.13], primary 98.75%. Similar cues do alter geometry, and low-load point estimates are worse, but a high-load retention penalty is inconclusive. Do not call these conditions equivalent or claim reproduction of the Chen et al. phenotype.', '',
        'Randomized K6 has the same certified load as native K6. Native minus randomized K6 retention at the difficult condition is +1.69 pp [-1.01,4.37], descriptive 95%; no clear native-wiring advantage is established there.', '',
        '## Prespecified primary contrasts', '',
        'All four are paired across 32 independent blocks, constant-per-pair exposure. Intervals are nominal Bonferroni-adjusted 98.75% percentile bootstrap intervals. Numbers are percentage points.', '',
        '| Contrast | Estimate [interval] |', '|---|---:|']
    for key, label in [('hard_retention_k6_minus_k4', 'K6 minus K4, load16/overlap6 retention'), ('hard_noise_k6_minus_k4', 'K6 minus K4, load16/overlap6 noise .3'), ('k6_load16_minus_load2_similar', 'K6 load16 minus load2, overlap6'), ('k6_similar_minus_dissimilar_load16', 'K6 overlap6 minus overlap2, load16')]:
        lines.append(f'| {label} | {fmt(a["primary"][key])} |')
    lines += ['', '## Capability criterion and its limits', '',
        'Largest tested load with simultaneous lower bounds above .80 for both mean retention and immediate new learning, requiring every lower tested load to pass too. One-sided Bonferroni bootstrap bounds cover 160 checks across experimental models/conditions/endpoints at nominal familywise 95%; these are approximate bootstrap bounds. Certification concerns the final acquisition probe at noise .1, not post-reversal retention or stronger noise. No interpolation or extrapolation beyond 2/4/8/16 pairs. Failure to certify does not by itself prove the population mean is below .80.', '',
        '| Model | Overlap2, 128/pair | Overlap6, 128/pair | Overlap2, 512 total | Overlap6, 512 total |', '|---|---:|---:|---:|---:|']
    for family in FAMILIES[:5]:
        caps = [a['capacity'][f'{family}_s{s}_{regime}']['certified_load'] for regime in REGIMES for s in OVERLAPS]
        lines.append('| '+names[family]+' | '+' | '.join(map(str, caps))+' |')
    lines += ['',
        '**Passing this average criterion does not mean every memory is safe.** At load16/overlap6/128 per pair, mean worst-pair retention is only 11.35% for K6 and 26.77% for direct input. These are averages of each sequence\'s minimum pair probability; chance is 50%. Some memories are strongly reversed or lost even when average retention passes. The next intervention should report these tails, not optimize mean capacity alone.', '',
        'For K6/overlap6/128 per pair, simultaneous retention lower bounds at loads 2/4/8/16 are 93.84%, 85.56%, 84.71%, 73.66%; new-learning lower bounds all exceed 97%. The failure at load16 comes from retention, not the new-learning guardrail.', '',
        '## Joint profile at 16 similar pairs', '',
        '128 presentations per pair; mean percentages. “Forgetting” is immediate post-learning minus final retention in pp. Other profile intervals and paired comparisons are descriptive 95% and available in the linked analysis/CSV; only the four contrasts above have primary multiplicity control.', '',
        '| Model | New learning | Retention | Forgetting | Noise .3 | Reversed pairs | Unchanged after reversal |', '|---|---:|---:|---:|---:|---:|---:|']
    for family in FAMILIES:
        stats = a['profiles']['s6_per_pair_l16'][family]
        lines.append('| '+names[family]+' | '+' | '.join(f"{100*stats[m]['mean']:.2f}" for m in ('new_learning', 'retention', 'forgetting', 'noise_retention', 'reversal', 'unchanged_after_reversal'))+' |')
    lines += ['',
        'K6 improves new learning by +1.29 pp [0.67,2.08], reversal by +3.74 [0.77,6.74], and unchanged-pair retention after reversal by +6.40 [2.88,9.87] versus K4 (descriptive 95%). The retention gain does not come with a demonstrated new-learning or reversal deficit. Reversal still damages unchanged memories substantially; all pairs are probed after the entire reversal phase, so earlier reversed pairs can also suffer further interference.', '',
        f"Higher noisy-probe performance is distinct from a smaller noise penalty. In this condition the .1-to-.3 noise cost is {100*costs[:, 1].mean():.2f} pp for K6 and {100*costs[:, 0].mean():.2f} pp for K4; K6-minus-K4 cost is {fmt(noise_costs['k6_minus_k4_cost'])} pp, descriptive 95%. Thus K6 performs better at both noise levels, but its loss when noise increases is larger here. See the [supplementary noise-cost diagnostic](../results/exp006_confirmation/noise_costs.json); this post-confirmation decomposition does not replace the prespecified noisy-performance contrast.", '',
        'The oldest K6 pair in this condition retains 66.46% after 1,920 subsequent presentations (32.09 pp forgetting); pair8 retains 67.78% after 1,024 subsequent presentations; the newest retains 98.67% with zero subsequent presentations. The full memory-age table reports every pair; these are descriptive examples, not a fitted monotonic law.', '',
        '## Exposure and similarity controls', '',
        '| Load | Presentations/pair: constant-per-pair | Acquisition total | Presentations/pair: constant-total | Acquisition total | Additional reversal presentations |', '|---|---:|---:|---:|---:|---:|']
    for load in LOADS: lines.append(f'| {load} | 128 | {128*load} | {512//load} | 512 | {64*load} |')
    lines += ['',
        'At load16/overlap6, reducing exposure from 128 to 32 per pair changes K6 new learning from 98.65% to 95.43% and retention from 78.74% to 77.92%. K4 retention is 71.14% versus 73.33%; more training is not uniformly better for old memories. These descriptive exposure comparisons use coupled streams and are not new primary tests. All models receive identical input observations, potential rewards and choice uniforms; realized choices and hence observed rewards may differ.', '',
        'The cue family uses a shared 2- or 6-input core, exact within-pair intersection, and unique ten-active-input prototypes. Across-memory overlap is fully saved, not assumed equal to within-pair overlap. At load16 in the similar condition its mean intersection is 6.474/10, range 6–9. This manipulates clustered similarity across memories as well as within each pair; it does not isolate one type of similarity.', '',
        '![Retention with equal exposure per memory](../results/exp006_confirmation/retention_per_pair.png)', '',
        '![Retention with equal total acquisition exposure](../results/exp006_confirmation/retention_total.png)', '',
        'Shading is descriptive pointwise 95% block-bootstrap uncertainty. Dashed horizontal .80 is the mean-retention threshold, not a confidence bound; visual crossings do not define certified capacity.', '',
        '## Representation diagnostics and resource comparison', '',
        'At load16/overlap6/128 per pair, K6 noisy-to-clean representation cosine is .946 versus K4 .874; unused-cell fractions are 41.78% versus 57.79%. Between-memory clean cosine is slightly higher for K6 (.535 versus .525), while exact identical representations occur less often (.53% versus 4.25% of cross-memory comparisons). These descriptive features are compatible with a role for stability and feature reuse, but no mediation or unique cause has been established. Complete input overlaps, representation matrices and participation/stability summaries are retained in the raw arrays and [geometry report](../results/exp006_confirmation/geometry.json).', '',
        '| Model | Learned weights | Encoding work per cue | Other resources |', '|---|---:|---|---|',
        '| Native/random sparse | 146 | Executed dense 40×73 projection: 2,920 multiply-accumulate terms plus sorting 73 values; 365 nonzero anatomical edges | 73 cells, exactly K4 or K6 active; total activity 10 |',
        '| Direct input | 80 | Copy 40 clipped PN activities; no projection or winner sort | All input information available to the readout |',
        '| Identity oracle | 4L effective weights | True cue identity to one-hot feature; privileged validation control | 32 allocated features, only 2L used, never an experimental competitor |', '',
        'Three independently switched null circuits per block preserve both binary degree sequences and each KC\'s contact multiset. Each used 14,600 accepted switches (40 per native edge); overlap diagnostics at 10/20/30/40 sweeps are saved per block. These audits verify invariants and extensive switching, not uniformity over every admissible graph. Null replicates were averaged before inference, not counted as extra task blocks.', '',
        'All experimental families received the same eight development candidates. Selected eta/T: .003333/.1 for native/random K4/K6, .006667/.1 for direct input, .003333/.1 for oracle. One global setting per family; no condition-specific tuning. The grid is bounded and several choices are at its lower learning-rate edge, so this is not an optimized-capacity ceiling over all possible hyperparameters.', '',
        '## Validation, execution and deviations', '',
        f"Validation pilot: 18.40 seconds, 63.19 MB peak process memory; exact full-block replay. Confirmation block computations total {run['compute']['sum_block_cpu_seconds']:.2f} CPU seconds and {run['compute']['sum_block_wall_seconds']:.2f} summed worker-wall seconds with three workers; peak worker memory {run['compute']['peak_worker_memory_bytes']/1e6:.2f} MB; raw checkpoint storage {run['compute']['npz_bytes']/1e6:.2f} MB. Summed worker time is not elapsed campaign time and excludes the audit/replay. Development totals {dev['compute']['sum_block_cpu_seconds']:.2f} CPU seconds. No paid compute or separate workstation execution.", '',
        'Nine preflight tests cover streams/exposure, exact overlap/uniqueness, null invariants, independent scalar update reference, scalar versus batch sequence behavior, persistent boundary hashes, read-only probes, deterministic replay, oracle adequacy and metric definitions. All 6 development and 32 confirmation checkpoints pass checksums, regenerated task digests, continuity checks and metric recomputation. One complete block in each stage replays exactly, including arrays and boundary hashes. The oracle retains approximately 99% across the battery and has exactly zero acquisition forgetting, validating the task/reward pipeline when cues have separate features.', '',
        'Protocol timing deviation: the stream-independence preflight constructed prototype arrays for development block100/overlap6 and confirmation block1000/overlap6 before their stage contracts. No learner or performance evaluation used those fixtures before freeze, and no outcome-based tuning or sample replacement occurred. This is a deviation from literal input-generation timing, not evidence of a fully untouched-input preflight. Historical EXP-002–005 source/results were preserved.', '',
        'WindowsApps Python was unavailable, so execution used bundled CPython. CIM inventory was denied; platform, logical-processor count and process counters are recorded without inventing a hardware model. Rendering used the existing cached Matplotlib under read access escalation. No experimental sample failed or was excluded. Run records include source/configuration hashes, dirty-worktree commit context and reproducible stream definitions.', '',
        '## Decision and next milestone', '',
        'Close priority 2. K6 is certified through load8 and is not certified at load16; K4 reaches its certified boundary earlier. This identifies a boundary for the tested performance criterion, not an exact theoretical maximum or proof that K6 population-mean retention is below .80 at load16. Six-winner coding helps, but direct input and the oracle show headroom without adding cells. Severe worst-memory losses and reversal interference make durable retention the practical target.', '',
        'Proceed next to the already ordered priority 3: a separately frozen test of development-calibrated threshold/gain homeostasis across existing cells, compared with ordinary tuning and shuffled calibration. Use load8/load16, both exposure regimes and similarity conditions, and retain direct/random baselines. Require useful retention and tail behavior alongside new learning and reversal; reducing unused cells is not itself success. Do not claim homeostasis already helps, and do not start growth from this result alone. Cross-circuit validation follows a specific prediction.', '',
        'Scope remains one static larval anatomy, synthetic clustered cue pairs, and this chosen-action delta learner. The experiment limits the tested encoding-plus-learning system, not the theoretical information capacity of every 73-cell representation. Chen et al. found sleep-related pattern-separation impairment with disrupted sparse coding in flies; that motivates stress testing but is not a result reproduced here. [Chen et al., Current Biology (2026)](https://pubmed.ncbi.nlm.nih.gov/41844155/).']
    (ROOT/'experiments/EXP-006-results.md').write_text('\n'.join(lines)+'\n', encoding='utf-8')
    replace('experiments/EXP-006-design.md', '# EXP-006: persistent-memory benchmark design (not executed)', '# EXP-006: original persistent-memory benchmark design\n\nStatus update 2026-09-14: executed and audited under the [final frozen protocol](EXP-006-protocol.md). See [results](EXP-006-results.md). The prospective design below is retained as history.')
    replace('README.md', '**EXP-002 through EXP-005 complete and audited • 13 September 2026.**', '**EXP-002 through EXP-006 complete and audited • 14 September 2026.**\n\n[EXP-006 persistent-memory results](experiments/EXP-006-results.md): 32 confirmation blocks audited. At 16 similar pairs, native K6 retains 78.74% versus K4 71.14% (+7.60 pp [4.68,10.43], primary 98.75%). Initial learning stays high while old memories deteriorate. K6 passes the average-capacity criterion through 8 pairs; direct input through 16 with fewer learned weights. Individual memory losses remain severe. Next: balanced participation across existing cells; growth stays conditional.')
    replace('README.md', 'Next: [persistent-memory load and cue similarity](experiments/EXP-006-design.md), with direct-input and randomized sparse baselines.', 'The subsequent [persistent-memory benchmark](experiments/EXP-006-results.md) is now complete, including direct-input and randomized sparse baselines.')
    replace('README.md', 'Start with [EXP-005](experiments/EXP-005-results.md), then the historical EXP-004/003/002 reports. Priority 1 is complete; finalize and validate EXP-006 next.', 'Start with [EXP-006](experiments/EXP-006-results.md), then the historical EXP-005/004/003/002 reports. Priorities 1 and 2 are complete; design priority 3 homeostasis next.')
    replace('EXPERIMENTS.md', 'Updated 2026-09-13. **Four scientific experiments completed: EXP-002 baseline, EXP-003 confirmation, EXP-004 activity/population diagnostic and EXP-005 mechanism controls.**', 'Updated 2026-09-14. **Five scientific experiments completed: EXP-002 baseline, EXP-003 confirmation, EXP-004 activity/population diagnostic, EXP-005 mechanism controls and EXP-006 persistent memory.**')
    replace('EXPERIMENTS.md', 'EXP-006 is the next benchmark design, not an executed campaign.', 'EXP-006 passes nine preflight tests and audits of six development/32 confirmation blocks; [results](experiments/EXP-006-results.md).')
    replace('EXPERIMENTS.md', '| EXP-006 | [Persistent-memory load and similarity](experiments/EXP-006-design.md) | proposed design / not executed | EXP-005; final protocol and validation pending | Continuous retained weights, increasing load/similarity, direct-input and randomized sparse baselines |', '| EXP-006 | [Persistent-memory load and similarity](experiments/EXP-006-protocol.md) | completed / audited | Nine preflight tests; six development and 32 confirmation blocks | K6-K4 hard retention +7.60 pp [4.68,10.43], primary 98.75%; average criterion through 8 pairs for K6, 16 for direct input. [Results](experiments/EXP-006-results.md) |')
    replace('ROADMAP.md', 'Updated 2026-09-13.', 'Updated 2026-09-14.')
    replace('ROADMAP.md', '**Next is priority 2**, the [persistent-memory benchmark design](experiments/EXP-006-design.md), which has not run.', '**Priority 2 is also complete:** [EXP-006](experiments/EXP-006-results.md) finds cumulative forgetting despite strong initial learning. K6 helps at 16 similar pairs (+7.60 pp [4.68,10.43], primary 98.75%), but certifies only through 8 pairs versus direct input through 16. Next is priority 3 homeostasis; worst-memory losses must remain visible.')
    replace('ROADMAP.md', '2. **Next — persistent memory under increasing load and cue similarity.** Finalize and validate [EXP-006](experiments/EXP-006-design.md), then run fresh development and a frozen confirmation. Preserve weights across memories; probe every previously learned pair. Compare native K4/K6, direct-input delta and degree/contact-controlled randomized sparse N73 circuits. Separate constant exposure per memory from constant total exposure.', '2. **Complete — persistent memory under increasing load and cue similarity.** [EXP-006](experiments/EXP-006-results.md): six development/32 confirmation blocks audited; persistent weights, all-memory probes, direct and degree/contact-controlled random circuits, separate exposure regimes. Load degrades old memories despite strong initial learning; K6 improves retention/noise but direct input has more headroom. Extra high-load similarity penalty is inconclusive. No sample extension.')
    replace('ROADMAP.md', '3. **Then — balanced participation across existing cells.**', '3. **Next — balanced participation across existing cells.**')
    replace('ROADMAP.md', 'Next concrete action: finalize and validate the [EXP-006 persistent-memory benchmark](experiments/EXP-006-design.md). EXP-005 is complete; no old sample will be extended or retuned. See the [mechanism results](experiments/EXP-005-results.md).', 'Next concrete action: design and freeze priority 3 homeostasis against global tuning and shuffled calibration, using the [EXP-006 persistent-memory limit](experiments/EXP-006-results.md). Retain new learning, worst-memory retention, reversal, noise and direct/random baselines. EXP-005/006 are complete; no old sample will be extended or retuned.')
    replace('ROADMAP.md', 'EXP-005 now completes the bounded N73 update diagnostic; proceed to persistent-memory load/similarity before broader transfer or more growth.', 'EXP-005 and EXP-006 complete the activity diagnostic and persistent-memory benchmark; proceed to homeostasis before broader transfer or more growth.')
    replace('ROADMAP.md', '**What changed:** learning-rate adjustment does not remove the activity advantage. The next benchmark should test whether K6\'s greater noisy-cue stability remains useful as similar-cue overlap and memory load increase. The roadmap order is unchanged, and these results do not justify restarting growth.', '**What changed:** K6 remains useful under cumulative load and noise, but direct-input learning retains more with fewer learned weights. The observed problem is loss of old associations despite successful acquisition. An extra K6 similarity penalty at high load was not established. The roadmap order is unchanged; homeostasis must improve useful retention, not participation alone, and growth remains conditional.')
    prepend('CLAIMS_LEDGER.md', '# Claims ledger', '## EXP-006 additions — 2026-09-14\n\n- Supported in this synthetic continuous-memory assay: K6-K4 retention +7.60 pp [4.68,10.43] and noise retention +6.06 [3.61,8.31], primary 98.75%, at load16/overlap6/128 per pair.\n- Load causes substantial forgetting with acquisition preserved. Average-capacity criterion certifies K6 through 8 pairs and direct input through 16; this does not guarantee every memory.\n- Inconclusive: extra high-load similarity penalty and native-K6 retention advantage over randomized K6. Stability/participation/collisions remain descriptive, not unique mediation.\n- Homeostasis, transfer and growth benefits remain untested here. Evidence: [EXP-006](experiments/EXP-006-results.md), [audited run](research/runs/EXP-006-confirmation.json).')
    prepend('RESEARCH_LOG.md', '# Research log', '## 2026-09-14 — EXP-006 closes persistent-memory milestone\n\nUser authorized roadmap priority 2. Implemented and froze a continuous-memory challenge: loads2/4/8/16, shared core2/6, constant-per-pair/constant-total exposure, native K4/K6, direct input, three degree/contact-matched random circuits per block, oracle validation. Retained weights throughout acquisition/reversal; probed every old pair without updates. Nine preflight tests and exact validation replay passed; six development blocks selected global settings from equal eight-candidate grids; 32 confirmation blocks completed and audited without exclusions. No subagents or additional interventions.\n\nPrimary hard retention K6-K4 +7.60 pp [4.68,10.43]; noise advantage +6.06 [3.61,8.31]; K6 load16-load2 -18.22 [-22.21,-14.05]; K6 high-low similarity -0.02 [-5.21,5.13], all 98.75%. Initial learning remains high. Average-capacity criterion: native K6 through8, direct through16. Worst-memory losses are severe. Native K6 versus random K6 hard retention remains inconclusive.\n\nDisclosed timing deviation: a preflight stream test generated one development and one confirmation prototype fixture before stage freeze, without learning/performance inspection. WindowsApps Python failed before samples; bundled Python worked. CIM inventory denied; process/platform counters recorded. Plot cache required read escalation. Frozen EXP-002–005 sources/results preserved; source-hashed EXP-006 code/results retained. See [results](experiments/EXP-006-results.md), [protocol](experiments/EXP-006-protocol.md), [run](research/runs/EXP-006-confirmation.json).\n\nClose priority2. Next: separately calibrated homeostasis versus global tuning and shuffled calibration; retain mean/worst memory, new learning, reversal and noise. No immediate growth or transfer, no retuning of completed confirmation.')
    decision = '| D032 (2026-09-14) | Close user-authorized EXP-006; advance to priority 3 homeostasis | Persistent-memory load harms retention with initial learning preserved. K6 helps but direct input certifies a higher tested load with fewer weights. Extra high-load similarity penalty and native-vs-random retention advantage remain inconclusive. Optimize useful retention including worst-memory tails; growth and transfer remain in their existing order. [Results](experiments/EXP-006-results.md) |'
    if decision not in (ROOT/'DECISIONS.md').read_text(encoding='utf-8'):
        replace('DECISIONS.md', 'When reversing a decision,', decision+'\n\nWhen reversing a decision,')
    p = ROOT/'OPEN_QUESTIONS.md'; text = p.read_text(encoding='utf-8')
    old = 'Default next action: finalize and validate EXP-006 persistent-memory load/similarity, including direct-input and randomized sparse baselines. EXP-005 is complete; do not extend the completed samples. Test whether K6 stability remains useful when cue overlap and cumulative load increase.'
    if old in text: replace('OPEN_QUESTIONS.md', old, 'Next action: design priority 3 homeostasis from the [EXP-006 results](experiments/EXP-006-results.md). Can calibrated use of existing cells reduce cumulative forgetting and worst-memory failures beyond global tuning and shuffled calibration? K6 remains useful, direct input exposes further headroom, and an additional high-load similarity penalty remains unresolved. Do not extend completed samples.')
    replace('README.md', 'EXP-005 completed the bounded N73 mechanism milestone; the next step is persistent-memory load and cue similarity.', 'EXP-005 completed the bounded N73 mechanism milestone and EXP-006 completed persistent-memory load and similarity. The next step is calibrated participation across existing cells.')
    manifest = read(ROOT/'research/experiment_manifest.json')
    manifest['date'] = '2026-09-14'; manifest['scientific_experiments_completed'] = 5
    for e in manifest['experiments']:
        if e['id'] == 'EXP-006': e.update(status='completed', spec='experiments/EXP-006-protocol.md', runtime_measured=True, development_blocks_completed=6, confirmation_blocks_completed=32, validation_tests=9, results='experiments/EXP-006-results.md', run='research/runs/EXP-006-confirmation.json', primary=a['primary'], next_action='Design priority 3 homeostasis with retained learning/reversal/noise and worst-memory guardrails; growth remains conditional')
    write(ROOT/'research/experiment_manifest.json', manifest)


if __name__ == '__main__': main()
