"""Generate EXP-011 report and Session D handoff from audited frozen outcomes."""
from tools import run_compound_transfer as c

def ci(v):return f"{100*v['mean']:.2f} [{100*v['lower']:.2f}, {100*v['upper']:.2f}]"
def pct(v):return f"{100*v['mean']:.2f}"
def prepend(path,heading,body):
    p=c.ROOT/path;s=p.read_text(encoding='utf-8')
    if heading in s:return
    first,rest=s.split('\n',1);p.write_text(first+'\n\n'+heading+'\n\n'+body+'\n'+rest,encoding='utf-8')

def main():
    a=c.read(c.OUT/'analysis.json');s=c.read(c.OUT/'selection.json');audit=c.read(c.OUT/'audit.json')
    assert audit['passed'] and audit['blocks']==31
    p=a['tables']['native_calibrated'];gap=a['primary_gap'];loss=a['primary_forgetting']
    result=f"Native/calibrated offline old-context accuracy {ci(p['offline']['old'])}%; tuned sequential accuracy {ci(p['blocked']['old'])}%; paired gap {ci(gap)} pp; acquisition-to-final loss {ci(loss)} pp (95% intervals, 24 fresh blocks)."
    conclusion=("The prospective prediction is supported: useful nonlinear distinctions remain readable from frozen sparse representations while the tuned sequential readout loses previously learned associations." if a['prediction_passed'] else "The prospective prediction is not supported in this task. " + ("Inadequate recovery or task validation makes this uninformative about forgetting of otherwise recoverable information." if a['classification']=='uninformative_recovery_or_task' else "Adequate recovery does not establish the required sequential-learning deficit and acquisition-to-final loss; retain the failed or precision-limited prediction."))
    lines=['# EXP-011 / Session C — nonlinear compound-task transfer','', '2026-09-15. Complete, development-selected and freshly evaluated; automated self-audit passed. [Protocol](EXP-011-protocol.md), [selection](../results/exp011/selection.json), [analysis](../results/exp011/analysis.json), [audit](../results/exp011/audit.json).','', '## Conclusion','',conclusion,'',result,'',f"Classification: **{a['classification']}**. Held-out capable/direct gate: {a['capable_gate']}; sparse old-context recovery >=80%: {a['recovery_gate']}. All three primary criteria were required. No confirmation samples were added, excluded, replaced or used for tuning.",'', '## What changed from B','', 'This is supervised XOR classification with two continuous compound components, variable nuisance inputs and noisy fresh observations. Learning proceeds through two contexts in which the same second component has opposite labels. Both contexts contain both labels. There are no arbitrary cue-ID inputs or assigned cue-pair rewards. This tests interpolation to fresh observations/nuisance mixtures within four trained logical categories, not extrapolation to unseen logical combinations or natural sensory generalization. Context order, channel mapping and label polarity vary independently across blocks.','', 'The task was chosen and written before any outcomes because it tests context-dependent associations and nonlinear representation sufficiency. It was the only task tried. Development used six blocks, four learning rates per representation/schedule and four ridge penalties. Selection balances old and new final performance. No sparse-encoder or stimulus tuning occurred. Existing EXP-007 offsets were transferred unchanged; this is not task-specific recalibration.','', '## Primary endpoints and controls','', '| Native/calibrated average | Estimate [95% CI], % or pp |','|---|---:|',f"| Offline old-context accuracy | {ci(p['offline']['old'])} |",f"| Tuned blocked old-context accuracy | {ci(p['blocked']['old'])} |",f"| Paired offline minus blocked, pp | {ci(gap)} |",f"| Blocked acquisition accuracy | {ci(p['blocked']['acquisition'])} |",f"| Acquisition minus final old, pp | {ci(loss)} |",'', 'All intervals use independent task blocks, not individual probes or null instances. Native/calibrated and the three nulls are averaged within each block. The sample size was fixed at 24 before fresh outcomes. A planning SD of .10 implies about 4.2 pp half-width; actual intervals above determine precision. Secondary intervals are unadjusted descriptive comparisons.','', '| Representation | Offline old | Blocked old | Blocked new | Acquisition | Worst phase | Fixed B rate old |','|---|---:|---:|---:|---:|---:|---:|']
    for rep in ('native','calibrated','random','direct','polynomial'):
        t=a['tables'][rep];lines.append('| '+rep+' | '+' | '.join(pct(t[m][f]) for m,f in [('offline','old'),('blocked','old'),('blocked','new'),('blocked','acquisition'),('blocked','worst'),('fixed_B_blocked','old')])+' |')
    lines += ['', 'Values are percentages. Worst phase is computed per block, then averaged. Polynomial is a generic quadratic feature diagnostic with 861 signed coefficients; direct has 40, sparse has 73. Online stores two coefficient vectors (80, 146 or 1722 scalars); offline fits one signed vector. All core feature mean squared norms are 100/6 using training-only normalization for direct/polynomial. Fixed B rate is 1/150; the primary online comparator is ordinarily tuned, not that fixed anchor.','', '## Order, computation and historical access','', '| Representation | Shuffled one-pass old/new | Local10 old/new | Replay10 old/new | Unclipped old/new |','|---|---:|---:|---:|---:|']
    for rep in ('native','calibrated','random','direct','polynomial'):
        t=a['tables'][rep];lines.append('| '+rep+' | '+' | '.join(pct(t[m]['old'])+' / '+pct(t[m]['new']) for m in ('shuffled','local10','replay10','unclipped'))+' |')
    lines += ['', '| Native/calibrated paired contrast | pp [95% CI] |','|---|---:|']
    for key,v in a['contrasts']['native_calibrated'].items():lines.append(f'| {key} | {ci(v)} |')
    lines += ['', 'Every learner receives the same 256 observations and exact +/-1 labels. One-pass schedules perform 256 updates; local10 and replay10 perform 2560. Shuffled one-pass requires both contexts available together and full storage, but adds no updates. Local10 stores/repeats only the current 128-example context before switching; replay10 stores/revisits all 256. Thus replay-versus-local10 matches updates and unique data but changes historical access and ordering. It does not isolate storage from scheduling. Each schedule has the same four-candidate development opportunity; paired schedule contrasts include the effect of their separately selected rates. Unclipped comparisons likewise include retuning.','', 'The offline solver uses simultaneous full-history storage and a penalized least-squares objective. It receives no additional observations, feedback, or test fitting access, but is **an explanatory diagnostic, not an equal-budget competitor or a capacity upper bound**. Signed coefficients can be expressed as the difference of nonnegative readouts; clipping constrains the learning trajectory, not the set of expressible signed linear functions. CPU timings are aggregate task timings, not method-level efficiency rankings.','', '## Development, boundary results and selected settings','', '| Representation | Development offline overall, % | Ridge lambda | Selected blocked eta |','|---|---:|---:|---:|']
    for rep in c.REPS:lines.append(f"| {rep} | {100*s['development_offline'][rep]:.2f} | {s['lambdas'][rep]} | {s['etas'][rep]['blocked']} |")
    lines += ['',f"Development capable/direct gate: {s['development_gate']}; sparse adequacy: {s['sparse_development_adequate']}. All candidate outcomes are retained in development checkpoints; all schedule rates are in selection.json. The prediction and n=24 were frozen at {s['created_utc']}, before confirmation's contract and inputs.",'', '| Representation | Offline overall [95% CI], % | Offline high-noise old [95% CI], % |','|---|---:|---:|']
    for rep in ('native','calibrated','random','direct','polynomial'):
        t=a['tables'][rep]['offline'];lines.append(f"| {rep} | {ci(t['overall'])} | {ci(t['high_old'])} |")
    lines += ['',f"Calibrated minus native offline old: {ci(a['calibration_minus_native_offline_old'])} pp. This secondary comparison is not a confirmation of homeostasis benefit or equivalence. Direct linear behavior is a negative control on XOR expressibility. Polynomial recovery validates this synthetic task's learnability; poor direct performance is not evidence for anatomical superiority. Randomized controls must remain visible, including any results matching or exceeding anatomy.",'', '## Validation, audit and resources','', 'Five tests cover analytic XOR/direct and quadratic behavior, independent augmented-least-squares verification, clipped update arithmetic, probe noninterference, exact observation/update accounting, phase-local versus historical revisiting, balanced labels, independent validation inputs and training-only normalization. No fixture generates confirmation inputs. Every ridge fit enforces normal-equation relative residual <1e-9. Every stage freezes source and protocol hashes; confirmation also pins the selection hash. Audit regenerates every array and scientific summary exactly, checks checkpoint hashes and rebuilds analysis. This is an automated self-audit, not independent review.','', '| Stage | Blocks | Compute wall s | CPU s | Peak MiB | NPZ MiB |','|---|---:|---:|---:|---:|---:|']
    for stage in ('validation','development','confirmation'):
        rs=[c.read(p) for p in (c.OUT/stage).glob('block_*.json')]
        lines.append(f"| {stage} | {len(rs)} | {sum(r['wall_seconds'] for r in rs):.2f} | {sum(r['cpu_seconds'] for r in rs):.2f} | {max(r['peak_memory_bytes'] for r in rs)/2**20:.2f} | {sum(p.stat().st_size for p in (c.OUT/stage).glob('*.npz'))/2**20:.2f} |")
    lines += ['',f"Audit replayed {audit['blocks']} blocks / {audit['arrays']} arrays and verified {audit['preserved_files']} historical files unchanged in {audit['wall_seconds']:.2f} wall seconds. Preservation scope includes historical experiment documents, code/tests, top-level result JSON and stage contracts, prior audit manifests and all B raw blocks/checkpoints plus calibration. Older bulk NPZ archives were not reread; this is not a full repository audit. One local CPU worker and one BLAS thread, no paid compute or GPU. Computation counters exclude archive compression, file hashing, reporting and process startup. The 30-minute computation, 2-GiB memory and 1-GiB archive caps passed; audit has its own 30-minute cap.",'', 'No failed scientific runs or discarded outcomes. The first overbroad preservation scan was interrupted before tests or any scientific block; its scope was narrowed before validation (see execution notes). An independent five-test preflight had passed during that scan. An optional plotting-library availability check found matplotlib absent; the report uses numeric tables and no dependency installation was needed. Raw NPZ remains local and Git-ignored; compact checkpoints, code and reports are versionable.','', '## Interpretation and Session D handoff','',conclusion+' '+('This strengthens the empirical scope of the learning-procedure explanation beyond random pair association, but does not establish a new mechanism.' if a['prediction_passed'] else 'This limits the attempted generalization and does not supply the planned positive transfer evidence for a paper.'),'', 'Two-context XOR is deliberately small and highly structured. The evidence is conditional on one larval projection, fixed nulls and transferred offsets. Offline fitting does not identify a unique repair or prove that all useful information is preserved. Training rate, clipping, convergence, objective and scheduling remain distinguishable contributors. This does not fully explain EXP-007/008 homeostasis nulls or the difference from A. No biological advantage, scaling law, worldwide novelty or natural-task generality is established.','', 'Next authorized milestone, only on a later user request: D, following [precise handoff](../research/SESSION_D_HANDOFF.md). Critically check prior work and decide the manuscript scope; do not automatically launch more experiments. C ends here. No D work, manuscript draft, publishing, commit or push was performed.','', 'Recovery: with bundled Python, use `tools/run_compound_transfer.py confirmation`, `analyze`, `audit`; completed stages verify hashes and reuse blocks. Do not rerun `select`, change settings, extend n or overwrite historical experiments. To regenerate this report, set `PYTHONPATH=.` and execute `tools/report_compound_transfer.py`.']
    records=[c.read(c.OUT/'confirmation'/f'block_{b:03}.json')['representations'] for b in range(24)]
    calibration={field:c.interval([r['calibrated']['models'][f"blocked_{c.ETAS.index(s['etas']['calibrated']['blocked'])}"][field]-r['native']['models'][f"blocked_{c.ETAS.index(s['etas']['native']['blocked'])}"][field] for r in records]) for field in ('old','new','overall')}
    c.write(c.OUT/'secondary_calibration.json',dict(scope='prospectively secondary; unadjusted descriptive intervals',calibrated_minus_native_blocked=calibration))
    fixed={mode:{field:c.interval([sum(r[rep]['models'][mode+'_2'][field] for rep in c.REPS[:2])/2 for r in records]) for field in ('old','new')} for mode in c.MODES}
    fixed_contrasts={field:c.interval([sum(r[rep]['models']['replay10_2'][field]-r[rep]['models']['local10_2'][field] for rep in c.REPS[:2])/2 for r in records]) for field in ('old','new')}
    c.write(c.OUT/'fixed_rate_controls.json',dict(eta=c.ETAS[2],native_calibrated=fixed,replay10_minus_local10=fixed_contrasts))
    extra=['## Common-rate schedule control','', 'All rows use eta=1/150, with the same update rule, observations and feedback. Values average native/calibrated within each block.','', '| Schedule | Old accuracy [95% CI], % | New accuracy [95% CI], % |','|---|---:|---:|---:|']
    for mode,t in fixed.items():extra.append(f"| {mode} | {ci(t['old'])} | {ci(t['new'])} |")
    extra += ['',f"At the same rate and 2560 updates, replay10 minus local10 is {ci(fixed_contrasts['old'])} pp for old learning and {ci(fixed_contrasts['new'])} pp for new learning. This specifically compares revisiting stored old data against extra practice confined to the current context; data availability and order change together. The common-rate control was specified before C outcomes, and uses the archived fixed-anchor models. Numerical record: [fixed-rate controls](../results/exp011/fixed_rate_controls.json).",'']
    at=lines.index('## Development, boundary results and selected settings');lines[at:at]=extra
    interpretation=['## What the controls establish','',
        f"Randomized sparse offline old accuracy is {pct(a['tables']['random']['offline']['old'])}% versus {pct(p['offline']['old'])}% for native/calibrated. The result supports a shared sparse-feature/readout phenomenon and supplies no demonstrated anatomical advantage. The capable quadratic model reaches {pct(a['tables']['polynomial']['offline']['overall'])}% overall; direct linear reaches {pct(a['tables']['direct']['offline']['overall'])}% as expected for this XOR negative control.", '',
        f"The generic quadratic representation also reaches {pct(a['tables']['polynomial']['blocked']['old'])}% old accuracy with the tuned one-pass sequential procedure. Sequential failure is therefore not inevitable on this task: the deficit concerns an interaction between these sparse features and the tested update procedure. Quadratic features have 861 dimensions versus 73, so this does not isolate a single geometric mechanism or constitute an equal-parameter competitor.", '',
        f"A prospectively secondary comparison shows calibrated-minus-native tuned sequential old accuracy of {ci(calibration['old'])} pp, new accuracy {ci(calibration['new'])} pp and overall {ci(calibration['overall'])} pp (unadjusted). Both selected rates are identical. Calibration therefore shows a descriptive retention benefit in C even though offline recoverability barely changes. This is not the primary confirmatory claim, has no multiplicity-adjusted discovery status and does not establish causation for B or overturn the task-specific EXP-007/008 nulls. It argues against calling homeostasis universally ineffective. Numeric record: [secondary calibration](../results/exp011/secondary_calibration.json).", '',
        f"At the common B rate, revisiting old data raises old accuracy by {ci(fixed_contrasts['old'])} pp relative to the same number of phase-local updates, while new-context accuracy changes by {ci(fixed_contrasts['new'])} pp. The small new-learning cost is retained. Extra updates alone therefore do not account for that recovery in this control; the availability and ordering of old data matter together. Shuffled one-pass learning also improves old retention without extra updates, but requires all-context availability/storage.", '',
        'The selected native/calibrated blocked and unclipped rates are identical, and the archived selected blocked runs have zero clipping events. Their scores coincide: clipping is not necessary for the deficit in this selected regime. This does not erase clipping contributions in B or at other rates. Native/calibrated blocked tuning selects the lowest rate in the four-value grid; slower rates or other learners remain untested. No claim of optimally tuned online learning follows, and the confirmation grid was not widened.', '',
        f"Actual primary-gap half-width is {100*(gap['upper']-gap['lower'])/2:.2f} pp, wider than the planning example because block variability is larger. The interval still clears the five-point margin; the sample remains 24. High-noise offline recovery falls to {pct(p['offline']['high_old'])}%: good low-noise recovery is not universal noise robustness. Reported t intervals are untruncated and can slightly exceed 100% near ceilings; 100% observed quadratic accuracy is not a guarantee of perfect population performance.", '']
    at=lines.index('## Interpretation and Session D handoff');lines[at:at]=interpretation
    lines += ['', 'Access-accounting detail: the paired simulation materializes datasets and probes in memory for reproducibility; the schedule comparisons describe which labeled examples the update procedure is allowed to revisit, not measured streaming-memory savings. Direct and quadratic normalization uses a single scalar from all training inputs, including the later context, so those baselines have unlabeled lookahead for scale and are not strictly causal streaming baselines. Native/calibrated/random sparse norms are fixed without this lookahead; the primary sparse comparison is unaffected. Evaluation observations and labels never enter fitting or scale selection.']
    lines += ['', 'Record-check limitation: the unchanged legacy `tools/validate_foundation.py` stops at its hard-coded experiment-count assertion, which only accounts through EXP-009. It cannot validate the current B/C manifest schema. C scientific replay is passed; `tools/audit_compound_records.py` separately checks current manifests, source/selection/temporal integrity, derived controls, artifact hashes and local links. No full legacy-foundation pass is claimed.']
    (c.ROOT/'experiments/EXP-011-results.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
    handoff='''# Session D handoff — Session C complete

2026-09-15. C / EXP-011 is complete. Stop here; D has not started and publication is not authorized.

## Read first

- research/NEXT_SESSIONS_PLAN_2026-09-14.md, Session D and common contract.
- experiments/EXP-011-results.md and EXP-011-protocol.md.
- results/exp011/selection.json, analysis.json, audit.json; development and confirmation contracts/checkpoints.
- experiments/EXP-010-results.md, research/SESSION_B_COMPLETION.md; EXP-009 source/reproduction limitations.
- EXP-007/008 nulls and research/PAPER_ASSESSMENT_2026-09-14.md.

## C's exact conclusion

'''+conclusion+'\n\n'+result+f"\n\nClassification: {a['classification']}. All 24 predeclared blocks were retained, without extension or evaluation tuning. One task only, no task search.\n\n"+'''## Scope D must retain

- Two-context XOR generalizes to fresh continuous/noisy observations, not unseen logical combinations. It is more than new seeds of pair memory, but still a narrow synthetic discrimination.
- Full label and observation access are matched. Offline fits use full history, a different objective and solver; no equal-budget or capacity-bound claim.
- Shuffling adds storage/all-context availability, not updates. Local10 and replay10 each add tenfold computation; only replay revisits old data after the switch. Separately tuned schedules do not isolate order at a fixed rate.
- Native and calibrated are averaged for the primary claim; random instances are nested fixed controls. Read every direct/random/polynomial and new-learning result, including negative tradeoffs. No anatomy-superiority implication from direct linear XOR failure.
- Fixed historical compensation is transferred, not recalibrated. C does not fully explain homeostasis nulls, uniquely establish mediation or show novel biology.
- Audit is automated self-review, not independent replication. All 31 blocks replay exactly; archive hashes are in results/exp011/preservation.json and audit.json.

## Exact next action when D is authorized

Audit the claim-to-evidence mapping and primary literature around the actual result, including Abdelrahman's compensation work and Zou, Zang and Ji's sparse-expansion continual-learning study. Determine what is familiar and what, if anything, this specific prospective controlled evidence adds. Produce D's claim table, figure plan and justified manuscript/negative-report/closure decision. No automatic extra campaign, sample extension or novelty claim. A local draft is separate from publication.

## Recovery

Use bundled Python with tools/run_compound_transfer.py confirmation/analyze/audit; completed checkpoints verify source and archive hashes. Do not rerun select or change the frozen sample. Raw arrays remain locally available and ignored by Git. Regenerate records with tools/report_compound_transfer.py under PYTHONPATH=.; research/exp011_artifacts.json indexes outputs. Historical B deferral statements remain preserved as dated history and are superseded only for C by the current request.
'''
    handoff += '\n## Control findings and limitations D must explicitly assess\n\n'+ '\n'.join([
        f"- Random sparse offline old accuracy {pct(a['tables']['random']['offline']['old'])}% versus native/calibrated {pct(p['offline']['old'])}%; no demonstrated anatomical advantage.",
        f"- Quadratic features retain {pct(a['tables']['polynomial']['blocked']['old'])}% under tuned sequential learning: this is a sparse-feature/procedure interaction, not a universal online-learning failure. The quadratic dimension is 861 versus 73.",
        f"- Secondary calibrated-minus-native sequential old accuracy {ci(calibration['old'])} pp; new {ci(calibration['new'])} pp (unadjusted). Keep this descriptive benefit visible; do not generalize historical homeostasis nulls to all tasks or treat C as their full explanation.",
        f"- Common-rate replay10 minus local10 old {ci(fixed_contrasts['old'])} pp; new {ci(fixed_contrasts['new'])} pp. Same 2560 updates/labels, different historical access/order. Preserve the new-learning cost.",
        '- Selected native/calibrated blocked rates are at the minimum grid value. No grid extension occurred. Optimal-online or universal-interference claims are unsupported.',
        '- Selected native/calibrated blocked runs have zero clipping events and match unclipped scores. Clipping is unnecessary for this deficit, without excluding its effects in B.',
        '- Direct/quadratic normalization uses all training inputs (unlabeled future-context scale access); sparse norms are fixed. The simulator materializes paired datasets, so schedule memory/access descriptions are procedural allowances, not measured online-memory savings.',
        f"- High-noise offline old accuracy {pct(p['offline']['high_old'])}%; low-noise recoverability is conditional.",
        f"- Primary-gap half-width {100*(gap['upper']-gap['lower'])/2:.2f} pp exceeds the planning example, but the frozen threshold is cleared. No sample extension.",
        '- Interrupted pre-outcome broad hash scan, scoped replacement preservation audit and missing optional plotting library are documented in SESSION_C_EXECUTION.md. No C scientific outcome was lost.',
        '- Legacy validate_foundation.py has a stale manifest count/schema through EXP-009; it remains unchanged. Separate C record/link/hash checks are in results/exp011/record_audit.json. Do not describe the legacy validator as passing.'
    ])+'\n'
    (c.ROOT/'research/SESSION_D_HANDOFF.md').write_text(handoff,encoding='utf-8')
    (c.ROOT/'research/SESSION_C_COMPLETION.md').write_text('# Session C completion\n\n'+conclusion+'\n\n'+result+'\n\nRead [full report](../experiments/EXP-011-results.md) and [Session D handoff](SESSION_D_HANDOFF.md). All 31 blocks audited; stop after C. D has not started.\n',encoding='utf-8')
    body=conclusion+' '+result+' [EXP-011 report](experiments/EXP-011-results.md). C is complete; D has not started. Current user authorization supersedes the historical C deferral below. Next action only when requested: D per [handoff](research/SESSION_D_HANDOFF.md). No publication.'
    for path in ('README.md','ROADMAP.md','OPEN_QUESTIONS.md','EXPERIMENTS.md','CLAIMS_LEDGER.md','RESEARCH_LOG.md'):
        prepend(path,'## Current Session C status — 2026-09-15',body)
    prepend('DECISIONS.md','## 2026-09-15 — D040: execute and close Session C; stop before D',body+' Preserve all prior experiments and all C outcomes; no confirmation extension or task substitution.')
    prepend('BENCHMARK_SPEC.md','## EXP-011 compound-task extension — 2026-09-15','Two-context XOR, continuous factors/nuisance, 256 matched labeled observations, 24 independent evaluation blocks and direct/random/quadratic controls. Shuffled/local10/replay10 distinguish order, computation and historical access with the qualifications in '+ '[EXP-011](experiments/EXP-011-results.md). This is fresh-observation interpolation, not unseen-quadrant extrapolation.')
    prepend('SOFTWARE_AUDIT.md','## EXP-011 validation and replay — 2026-09-15',f"Five tests and {audit['blocks']} block replays passed; {audit['arrays']} arrays compared exactly and {audit['preserved_files']} historical files unchanged. Bundled NumPy CPU runtime. Automated self-audit, not independent validation. [Report](experiments/EXP-011-results.md).")
    prepend('DATA_PROVENANCE.md','## EXP-011 synthetic task provenance — 2026-09-15','Fresh root-11011 stage-separated synthetic compound-task streams; no new anatomical data. Reuses the hashed EXP-007 calibration archive and the three fixed randomized projections used by B. No evaluation-specific calibration. Inputs, labels, channel permutations and schedule indices are locally archived under results/exp011. [Protocol](experiments/EXP-011-protocol.md).')
    prepend('research/NEXT_SESSIONS_PLAN_2026-09-14.md','## Execution status — 2026-09-15','Sessions A, B and C are complete. [C report](../experiments/EXP-011-results.md); [D handoff](SESSION_D_HANDOFF.md). The original plan below is retained. D has not started; no publication is authorized.')
    prepend('FAILED_PATHS.md','## EXP-011 boundaries and negative controls — 2026-09-15',f"Prediction classification: {a['classification']}. Direct linear XOR failure is expected and retained, not grounds for an anatomy-advantage claim. Read all control outcomes and high-noise limits in [EXP-011](experiments/EXP-011-results.md); no task substitutions or dropped evaluations. Missing optional matplotlib only affected figure availability, not execution.")
    m=c.read(c.ROOT/'research/experiment_manifest.json')
    if not any(e['id']=='EXP-011' for e in m['experiments']):
        m['experiments'].append(dict(id='EXP-011',session='C',status='completed_audited',spec='experiments/EXP-011-protocol.md',results='experiments/EXP-011-results.md',prediction_passed=a['prediction_passed'],classification=a['classification'],next='Stop; D only when requested'))
        m['scientific_experiments_completed']=10;c.write(c.ROOT/'research/experiment_manifest.json',m)
    c.write(c.ROOT/'research/runs/EXP-011-compound-transfer.json',dict(status='completed_audited',created_utc=c.stamp(),summary=result,classification=a['classification'],report='experiments/EXP-011-results.md',handoff='research/SESSION_D_HANDOFF.md',next='Stop after C'))
    paths=[p for p in c.OUT.rglob('*') if p.is_file() and 'frozen_source' not in p.parts and p.name!='record_audit.json']
    paths += [c.ROOT/p for p in ('experiments/EXP-011-protocol.md','experiments/EXP-011-results.md','tools/run_compound_transfer.py','tools/report_compound_transfer.py','tools/audit_compound_records.py','tests/test_exp011.py','research/SESSION_C_COMPLETION.md','research/SESSION_D_HANDOFF.md','research/SESSION_C_EXECUTION.md','research/runs/EXP-011-compound-transfer.json')]
    c.write(c.ROOT/'research/exp011_artifacts.json',{p.relative_to(c.ROOT).as_posix():dict(sha256=c.sha(p),bytes=p.stat().st_size) for p in paths})
    print(conclusion);print(result)

if __name__=='__main__':main()
